import type { NativeChatChannel, NativeChatMessage } from '../domain/types';

export const NATIVE_CHAT_UI_MOCK_ACCOUNT_ID = 'qa-self';

const SELF_ID = NATIVE_CHAT_UI_MOCK_ACCOUNT_ID;
const BASE_TIME = 1717800000000;
const MOCK_IMAGE_URI = 'https://reactnative.dev/img/tiny_logo.png';

export const nativeChatUiMockChannels: NativeChatChannel[] = [
  {
    accountGlobalMetaId: SELF_ID,
    avatar: 'https://www.idchat.io/logo.png',
    id: 'ui-metaweb-builders',
    lastMessage: {
      content: 'Retry should stay visible when broadcast fails.',
      kind: 'text',
      senderGlobalMetaId: SELF_ID,
      senderName: 'You',
      timestamp: BASE_TIME + 180_000,
    },
    lastReadIndex: 41,
    roomJoinType: '0',
    serverData: {
      memberCount: 128,
      unreadMentionCount: 2,
    },
    title: 'MetaWeb Builders',
    type: 'group',
    unreadCount: 5,
    updatedAt: BASE_TIME + 180_000,
  },
  {
    accountGlobalMetaId: SELF_ID,
    avatar: 'https://www.idchat.io/logo.png',
    id: 'ui-lisa-hahn',
    lastMessage: {
      content: 'Yes, the outgoing avatar confirms it.',
      kind: 'text',
      senderGlobalMetaId: SELF_ID,
      senderName: 'You',
      timestamp: BASE_TIME + 150_000,
    },
    lastReadIndex: 12,
    publicKeyStr: '04ui-lisa-hahn-public-key',
    serverData: {
      userInfo: {
        avatar: 'https://www.idchat.io/logo.png',
        globalMetaId: 'ui-lisa-hahn',
        name: 'Lisa Hahn',
      },
    },
    title: 'Lisa Hahn',
    type: 'private',
    unreadCount: 0,
    updatedAt: BASE_TIME + 150_000,
  },
  {
    accountGlobalMetaId: SELF_ID,
    avatar: 'https://www.idchat.io/logo.png',
    id: 'ui-bitcoin-circle',
    lastMessage: {
      content: MOCK_IMAGE_URI,
      kind: 'image',
      senderGlobalMetaId: 'nina-xu',
      senderName: 'Nina',
      timestamp: BASE_TIME + 30_000,
    },
    lastReadIndex: 7,
    roomJoinType: '0',
    serverData: {
      memberCount: 64,
      unreadMentionCount: 0,
    },
    title: 'Bitcoin Circle',
    type: 'group',
    unreadCount: 1,
    updatedAt: BASE_TIME + 30_000,
  },
];

export const nativeChatUiMockMessages: NativeChatMessage[] = [
  {
    accountGlobalMetaId: SELF_ID,
    chain: 'mvc',
    channelId: 'ui-metaweb-builders',
    channelType: 'group',
    content: 'The tx should be visible like IDChat.',
    contentType: 'text/plain',
    index: 42,
    kind: 'text',
    protocol: 'simplegroupchat',
    senderAvatar: 'https://www.idchat.io/logo.png',
    senderGlobalMetaId: 'nina-xu',
    senderName: 'Nina Xu',
    status: 'sent',
    timestamp: BASE_TIME + 60_000,
    txId: '9f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8091a2b3c4d5e6f708192a0c18',
  },
  {
    accountGlobalMetaId: SELF_ID,
    chain: 'mvc',
    channelId: 'ui-metaweb-builders',
    channelType: 'group',
    content: 'Right side also shows my current account avatar.',
    contentType: 'text/plain',
    index: 43,
    kind: 'text',
    protocol: 'simplegroupchat',
    senderAvatar: 'https://www.idchat.io/logo.png',
    senderGlobalMetaId: SELF_ID,
    senderName: 'You',
    status: 'sent',
    timestamp: BASE_TIME + 90_000,
    txId: 'a8d142e9987b4f21c0fd47322d10d57a65e7d62ab831775ef0da1ff0b76990b',
  },
  {
    accountGlobalMetaId: SELF_ID,
    chain: 'doge',
    channelId: 'ui-bitcoin-circle',
    channelType: 'group',
    attachmentUri: MOCK_IMAGE_URI,
    content: MOCK_IMAGE_URI,
    contentType: 'image/png',
    index: 8,
    kind: 'image',
    localPreviewUri: MOCK_IMAGE_URI,
    protocol: 'simplefilegroupchat',
    senderAvatar: 'https://www.idchat.io/logo.png',
    senderGlobalMetaId: 'nina-xu',
    senderName: 'Nina',
    status: 'sent',
    timestamp: BASE_TIME + 30_000,
    txId: 'd94b7d2c9987b4f21c0fd47322d10d57a65e7d62ab831775ef0da1ff0b76919a',
  },
  {
    accountGlobalMetaId: SELF_ID,
    chain: 'btc',
    channelId: 'ui-lisa-hahn',
    channelType: 'private',
    content: 'Are you testing with the right account?',
    contentType: 'text/plain',
    index: 13,
    kind: 'text',
    protocol: 'simplemsg',
    senderAvatar: 'https://www.idchat.io/logo.png',
    senderGlobalMetaId: 'ui-lisa-hahn',
    senderName: 'Lisa Hahn',
    status: 'sent',
    timestamp: BASE_TIME + 120_000,
    txId: '18fe5c2d9987b4f21c0fd47322d10d57a65e7d62ab831775ef0da1ff0b7694b9',
  },
  {
    accountGlobalMetaId: SELF_ID,
    channelId: 'ui-lisa-hahn',
    channelType: 'private',
    content: 'Yes, the outgoing avatar confirms it.',
    contentType: 'text/plain',
    kind: 'text',
    mockId: 'ui-pending-outgoing',
    protocol: 'simplemsg',
    senderAvatar: 'https://www.idchat.io/logo.png',
    senderGlobalMetaId: SELF_ID,
    senderName: 'You',
    status: 'pending',
    timestamp: BASE_TIME + 150_000,
  },
  {
    accountGlobalMetaId: SELF_ID,
    channelId: 'ui-metaweb-builders',
    channelType: 'group',
    content: 'Retry should stay visible when broadcast fails.',
    contentType: 'text/plain',
    errorMessage: 'Broadcast failed. Tap to retry.',
    kind: 'text',
    mockId: 'ui-failed-outgoing',
    protocol: 'simplegroupchat',
    senderAvatar: 'https://www.idchat.io/logo.png',
    senderGlobalMetaId: SELF_ID,
    senderName: 'You',
    status: 'failed',
    timestamp: BASE_TIME + 180_000,
  },
];
